name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.11'
    steps:
      - uses: actions/checkout@v3

      - name: Fetch tags upstream
        # Needs to fetch the tags from upstream to get the
        # correct version with setuptools_scm
        run: |
          git remote add upstream https://github.com/hyperspy/exspy.git
          git fetch --prune --unshallow
          git fetch upstream --tags

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Display version
        run: |
          python --version
          pip --version

      - name: Install pypa/build pypa/twine
        run: |
          pip install build twine

      - name: Build a binary wheel and a source tarball
        run: |
          python -m build

      - name: Display content dist folder
        run: |
          ls -l dist/
      
      - name: Run twin check
        run: |
          twine check dist/*

      - uses: actions/upload-artifact@v3
        with:
          path: ./dist/*
          name: dist

  test:
    name: Test Packaging
    needs: build
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.11'
    steps:
      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: actions/download-artifact@v3

      - name: Display content working folder
        run: |
          ls -R

      - name: Install distribution
        run: |
          pip install --pre --find-links dist exspy[tests]

      - name: Test distribution
        run: |
          pytest --pyargs exspy
